[package]
name = "tank01-data"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
utils = { path = "../utils" }
nfl-model = { path = "../nfl-model" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing.workspace = true

[dev-dependencies]
time = { workspace = true, features = ["serde-human-readable"] }
tokio = { workspace = true, features = ["test-util"] }
tempfile = { workspace = true }
wiremock = { workspace = true }
